### PR TITLE
New changes

### PR DESCRIPTION
**Pull request by DVJY**
first pull

### CODE REVIEW

**Review by DVJY — COMMENTED** [review]
ok

**Review by DVJY — COMMENTED** [review]
ok

**Review by DVJY — COMMENTED** [review]
ok

**Review by DVJY — COMMENTED** [review]
ok

**Review by DVJY — COMMENTED** [review]
ok

**Review by DVJY — COMMENTED** [review]
changes incorporated

**Review by DVSD1 — APPROVED** [review]
ok

**Comment by DVJY** [comment]
merge

**Pull request merged**
